---
title: "Regressions"
author: "Rémi Thériault"
date: "August 29, 2022"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Regressions}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r , include=FALSE}
library(knitr)

pkgs <- c("rempsyc")
successfully_loaded <- vapply(pkgs, requireNamespace, FUN.VALUE = logical(1L), quietly = TRUE)
can_evaluate <- all(successfully_loaded)

if (can_evaluate) {
  knitr::opts_chunk$set(eval = TRUE)
  vapply(pkgs, require, FUN.VALUE = logical(1L), quietly = TRUE, character.only = TRUE)
} else {
  knitr::opts_chunk$set(eval = FALSE)
}
```


## Regression example

```{r reg, message = FALSE}
# Load libraries
library(lavaan)
library(lavaanExtra)

# Define our regression terms
regression <- list(
  mpg = names(mtcars)[2:5],
  disp = names(mtcars)[4:7]
)

# Write the model, and check it
mtcars.model <- write_lavaan(regression = regression)
cat(mtcars.model)

# Fit the model with `lavaan`
fit.reg <- sem(mtcars.model, data = mtcars)

# Get regression parameters only
lavaan_reg(fit.reg)

# We can get it prettier with the `rempsyc::nice_table` integration
lavaan_reg(fit.reg, nice_table = TRUE, highlight = TRUE)
```
